# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.


# Disable startup message
startup_message off

# Create initial window
screen -t shell1 0
stuff "cd target/server0/bin^M"
stuff "./artemis run ^M"

# Create vertical split (left and right columns)
split -v

# Setup left column - 1 horizontal split (2 regions total)
focus left
split
focus down
screen -t shell2 1
stuff "cd target/server1/bin^M"
stuff "sleep 5^M"
stuff "./artemis run ^M"


# Setup right column - 4 horizontal splits (5 regions total)
focus right
screen -t shell3 2
stuff "sleep 10^M"
stuff "./target/server0/bin/artemis queue stat --sleep 1000^M"
split
focus down
screen -t shell4 3
stuff "sleep 10^M"
stuff "./target/server1/bin/artemis queue stat --sleep 1000^M"

# Return focus to top-left region
focus top
focus left
